# Generated by Django 4.1.5 on 2023-01-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('user', '0002_salesorders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorders',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
